In [ ]:
using LinearAlgebra
m = 3;
A = randn(m,m);
v = zeros(m,m);
u = zeros(m,m);
temp = zeros(m,1);
p(x,y) = (dot(x,y)/dot(y,y))*y #projection of vector x on vector y
for i in 1:m
    v[:,i] = A[:,i]
end
u[:,1] = v[:,1];
u[:,2] = v[:,2] - p(v[:,2],u[:,1]);
u[:,3] = v[:,3] - p(v[:,3],u[:,1]) - p(v[:,3],u[:,2]);

In [ ]:
print(dot(u[:,2],u[:,3]))

In [ ]:
for i in 1:2
    u[:,3] = v[:,3] - p(v[:,3],u[:,i]);

In [ ]:
u2-(v2 - p(v2,u1))

In [ ]:
A

In [33]:
using LinearAlgebra

m = 1000
temp = zeros(m,1)
u = zeros(m,m)
A = randn(m,m)

#projection of vector x on vector y
p(x,y) = (dot(x,y)/dot(y,y))*y

for i in 1:m
    j = i
    temp = A[:,i]
    while j > 1
        j = j - 1
        temp = temp - p(temp,u[:,j])
    end
    u[:,i] = temp/norm(temp)
end

In [34]:
u

1000×1000 Array{Float64,2}:
 -0.0011457     0.0182141     0.0371483    …   0.0327579    0.00651282
  0.0822972    -0.0200994     0.0186045        0.0369356    0.0364774 
 -0.000399931   0.0746063    -0.081111         0.0653549    0.0395389 
 -0.0219477    -0.036932     -0.0297845        0.0508492    0.00927233
  0.0103467    -0.0126903    -0.0141083        0.0704967   -0.0634614 
 -0.0201849     0.00260436   -0.0222613    …   0.031704     0.00130993
 -0.0418426    -0.0303777     0.00200847      -0.0396637   -0.00118771
  0.0469584     0.0198429     0.00952924       0.022256     0.0491908 
 -0.0213098    -0.0202316    -0.0144679        0.00388436  -0.0015332 
 -0.000830436  -0.0321612    -0.000306613      0.0325781   -0.0653398 
 -0.00665188    0.00450098    0.0375843    …  -0.00433361  -0.0461154 
  0.0477221    -0.0613348    -0.0828874       -0.03632      0.0136586 
  0.0238068     0.0290771     0.0223906        0.0165783    0.0507456 
  ⋮                                        ⋱     

In [28]:
#Classical Gram-Schmidt Algorithm

using LinearAlgebra

m = 500
temp = zeros(m,1)
Q = zeros(m,m)
R = zeros(m,m)
A = randn(m,m)

#projection of vector x on vector y
p(x,y) = (dot(x,y)/dot(y,y))*y

for i in 1:m
    v = A[:,i]
    for j = 1:i-1
        R[j,i] = dot(Q[:,j], A[:,i])
        v = v - R[j,i]*Q[:,j]
    end
    R[i,i] = norm(v)
    Q[:,i] = v/norm(v)
end

In [30]:
dot(Q[:,400],Q[:,478])

-6.086710996333622e-16

In [4]:
#Modified Gram-Schmidt Algorithm

using LinearAlgebra

m = 500
Q = zeros(m,m)
R = zeros(m,m)
A = randn(m,m)

#projection of vector x on vector y
p(x,y) = (dot(x,y)/dot(y,y))*y

for i in 1:m
    v = A[:,i]
    for j = 1:i-1
        R[j,i] = dot(Q[:,j], v)
        v = v - R[j,i]*Q[:,j]
    end
    R[i,i] = norm(v)
    Q[:,i] = v/norm(v)
end

In [5]:
R

500×500 Array{Float64,2}:
 22.1978   0.644536  -0.354733  …   0.856138    -1.15947     0.511489
  0.0     21.2599    -0.361727     -0.353212     0.199197   -0.753292
  0.0      0.0       21.4122        0.698349     0.394146    0.231447
  0.0      0.0        0.0          -0.938626     1.62276     0.151275
  0.0      0.0        0.0          -1.65124      1.25223     2.11302 
  0.0      0.0        0.0       …  -1.05906      0.919685   -0.537252
  0.0      0.0        0.0           0.00177685   0.938728   -0.252029
  0.0      0.0        0.0          -2.07886      0.643059   -0.59497 
  0.0      0.0        0.0          -1.14673     -2.13023     0.623312
  0.0      0.0        0.0          -1.70066     -1.36282    -0.268954
  0.0      0.0        0.0       …  -0.534275     0.615198    0.438148
  0.0      0.0        0.0          -2.29079      1.04872     0.775531
  0.0      0.0        0.0           1.16478     -0.262231    0.354118
  ⋮                             ⋱                               

In [3]:
dot(Q[:,3],Q[:,5])

-3.2559946492455305e-18

In [188]:
#Householder Transformation

m = 4
Q = 1.0*Matrix(I, m, m)
Q1 = 1.0*Matrix(I, m, m)
A = randn(m, m)
R = A

e1 = zeros(m)
e1[1] = 1.0

u = A[:,1] + sign(A[1,1])norm(A[:,1])e1
v = u/norm(u)
F = I - 2v*v'
R[1:end,1:end] = F*R[1:end,1:end]
Q1[1:end,1:end] = F[1:end,1:end]
Q = Q1*Q

4×4 Array{Float64,2}:
 -0.935014   -0.233957    -0.265198   -0.0261295 
 -0.233957    0.971713    -0.0320642  -0.00315923
 -0.265198   -0.0320642    0.963654   -0.0035811 
 -0.0261295  -0.00315923  -0.0035811   0.999647  

In [189]:
Q1 = 1.0*Matrix(I, m, m)
e2 = zeros(m-1)
e2[1] = 1.0
v = R[2:end,2] + sign(R[2,2])*norm(R[2:end,2])*e2
v = v/norm(v)
F = I - 2*v*v'
R[2:end,2:end] = F*R[2:end,2:end]
Q1[2:end,2:end] = F[1:end,1:end]
Q = Q1*Q
dot(Q[:,1],Q[:,2])

6.938893903907228e-17

In [190]:
Q1 = 1.0*Matrix(I, m, m)
e3 = zeros(m-2)
e3[1] = 1.0
v = R[3:end,3] + sign(R[3,3])*norm(R[3:end,3])*e3
v = v/norm(v)
F = I - 2*v*v'
R[3:end,3:end] = F*R[3:end,3:end]
Q1[3:end,3:end] = F[1:end,1:end]
Q = Q1*Q

4×4 Array{Float64,2}:
 -0.935014   -0.233957  -0.265198  -0.0261295
 -0.0259711  -0.498713   0.5937    -0.630977 
  0.345802   -0.532247  -0.722702  -0.273561 
  0.0741272  -0.642855   0.234291   0.7255   

In [231]:
m = 6
Q = 1.0*Matrix(I,m,m)
A = randn(m,m)
R = deepcopy(A)
for i in 1:m-1
    #create the unit vector along which reflection is desired
    e = zeros(m-i+1)
    e[1] = 1.0
    
    #create the projection matrix about plane perpendicular to v
    #this reflects the ith column of A and gives the ith column of Q 
    v = R[i:end,i] + sign(R[i,i])*norm(R[i:end,i])*e
    v = v/norm(v)
    F = I - 2*v*v'
    
    #create Qi = Qi-1 * ... Q3 * Q2 * Q1
    #it has the form Q = [I 0;0 F]
    Q1 = 1.0*Matrix(I, m, m)
    Q1[i:end,i:end] = F[1:end,1:end]
    Q = Q1*Q
    
    #create R
    R[i:end,i:end] = F*R[i:end,i:end]
end
Q = Q';

In [233]:
Q*R - A

6×6 Array{Float64,2}:
  1.47105e-15   1.33227e-15   2.22045e-16  …   4.16334e-17   8.88178e-16
 -8.88178e-16   0.0          -4.44089e-16      3.05311e-16  -6.66134e-16
  4.44089e-16  -1.55431e-15  -7.21645e-16      1.11022e-16  -4.44089e-16
  8.88178e-16   1.11022e-15   4.44089e-16     -2.22045e-16   1.11022e-16
 -2.22045e-16  -1.66533e-16   3.33067e-16      0.0          -6.34909e-16
  1.11022e-16   2.22045e-16   1.11022e-16  …  -1.11022e-16   8.32667e-17

In [220]:
A

6×6 Array{Float64,2}:
 -0.673313   1.80887    -0.190228   -0.0384109   0.653684   0.91424 
  1.59348   -0.0586789  -1.4138     -1.63921     0.806982  -0.139544
  1.1063    -0.455713   -0.0319577  -1.01237    -0.807085  -1.08195 
  0.765978  -0.119828   -1.66477    -0.843201    0.475535   0.727962
  0.384767   1.3026      0.0287265  -1.503       0.981132   0.847528
 -0.944449   0.305023    1.28962    -0.363126   -0.460456  -0.252057

In [198]:
dot(Q[:,1],Q[:,3])

-2.949029909160572e-16

In [205]:
size(Q)[1]

600